package formula;

import javax.swing.JOptionPane;
import DB.DatabaseConnection;
import java.sql.*;

public class audience extends javax.swing.JFrame {
        static Connection conn;
        static Statement st;
        static PreparedStatement ps;
        static String sql;
        static ResultSet rs;
        
        String gbs;
        
    public audience() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DatabaseConnection().setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx_firstname = new javax.swing.JTextField();
        tx_lastname = new javax.swing.JTextField();
        tx_ticketid = new javax.swing.JTextField();
        ag = new javax.swing.JComboBox<>();
        colorcombo = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tx_city = new javax.swing.JTextField();
        tx_nophone = new javax.swing.JTextField();
        btn_delmod = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Audience Form");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 45, 670, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Firstname");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 220, 59, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Lastname");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 260, 59, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ticket ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 140, 54, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Ticket Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 170, 72, 24);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 310, 23, 17);
        jPanel1.add(tx_firstname);
        tx_firstname.setBounds(207, 217, 285, 30);
        jPanel1.add(tx_lastname);
        tx_lastname.setBounds(207, 255, 285, 30);
        jPanel1.add(tx_ticketid);
        tx_ticketid.setBounds(204, 131, 285, 30);

        ag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42" }));
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        jPanel1.add(ag);
        ag.setBounds(207, 312, 50, 22);

        colorcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yellow", "Red", "Blue" }));
        colorcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorcomboActionPerformed(evt);
            }
        });
        jPanel1.add(colorcombo);
        colorcombo.setBounds(207, 170, 80, 22);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(210, 440, 73, 25);

        jButton2.setText("Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 440, 95, 25);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("City");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 350, 90, 20);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Number Phone");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 400, 90, 16);
        jPanel1.add(tx_city);
        tx_city.setBounds(207, 344, 285, 30);
        jPanel1.add(tx_nophone);
        tx_nophone.setBounds(205, 388, 287, 30);

        btn_delmod.setText("Delete and Update");
        btn_delmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delmodActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delmod);
        btn_delmod.setBounds(500, 130, 137, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\formula\\src\\gambar\\f1.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 690, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menu obj = new menu();
        obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String fname = tx_firstname.getText();
        if(tx_city.getText().equals("") || tx_firstname.getText().equals("") || tx_lastname.getText().equals("") ||
            tx_nophone.getText().equals("") ||tx_ticketid.getText().equals("") ||
            colorcombo.getSelectedItem().equals(false) || ag.getSelectedItem().equals(false)){
        JOptionPane.showMessageDialog(this, "please fill all the coloumn");
        }else{
        try{
            sql = "INSERT INTO tbl_penonton VALUES (?, ?, ?, ?, ?, ?, ?) ";
            ps =conn.prepareStatement(sql);
            ps.setString(1, tx_ticketid.getText());
            ps.setString(2, colorcombo.getSelectedItem().toString());
            ps.setString(3, fname);
            ps.setString(4, tx_lastname.getText());
            ps.setString(5, ag.getSelectedItem().toString());
            ps.setString(6, tx_city.getText());
            ps.setString(7, tx_nophone.getText());
            int rt = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Success");
        }catch (Exception e){
            System.out.println("Error"+e.getMessage());
            JOptionPane.showMessageDialog(this, "You cant enter the same ID ticket");
        }
        }
        tx_city.setText("");
        tx_firstname.setText("");
        tx_lastname.setText("");
        tx_nophone.setText("");
        tx_ticketid.setText("");
    }//GEN-LAST:event_btn_submitActionPerformed

    private void colorcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorcomboActionPerformed

    private void btn_delmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delmodActionPerformed
        // TODO add your handling code here:
        new deleteaud().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_delmodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(audience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(audience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(audience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(audience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new audience().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ag;
    private javax.swing.JButton btn_delmod;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> colorcombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tx_city;
    private javax.swing.JTextField tx_firstname;
    private javax.swing.JTextField tx_lastname;
    private javax.swing.JTextField tx_nophone;
    private javax.swing.JTextField tx_ticketid;
    // End of variables declaration//GEN-END:variables

private void gblhksg(){
    if(tx_city.getText().equals("") || tx_firstname.getText().equals("") || tx_lastname.getText().equals("") ||
            tx_nophone.getText().equals("") ||tx_ticketid.getText().equals("") ||
            colorcombo.getSelectedItem().equals(false) || ag.getSelectedItem().equals(false)){
        JOptionPane.showMessageDialog(this, "please fill all the coloumn");
    }
}


}
