package formula;

import javax.swing.JOptionPane;
import DB.DatabaseConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class deleteaud extends javax.swing.JFrame {
        static Connection conn;
        static Statement st;
        static PreparedStatement ps;
        static String sql;
        static ResultSet rs;
    public deleteaud() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DatabaseConnection().setConnection();
        
        tx_city.setEnabled(false);
        tx_firstname.setEnabled(false);
        tx_lastname.setEnabled(false);
        tx_nophone.setEnabled(false);
        colorcombow.setEnabled(false);
        ag.setEnabled(false);
        
        btn_delete.setEnabled(false);
        btnUp.setVisible(false);
        
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx_firstname = new javax.swing.JTextField();
        tx_lastname = new javax.swing.JTextField();
        tx_ticketid = new javax.swing.JTextField();
        ag = new javax.swing.JComboBox<>();
        colorcombow = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tx_city = new javax.swing.JTextField();
        tx_nophone = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_upd = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btn_delmode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete or Update Audience");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 45, 1205, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Firstname");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(67, 214, 59, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Lastname");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(67, 246, 59, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ticket ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(67, 141, 54, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Ticket Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(67, 170, 83, 24);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(67, 275, 23, 17);
        jPanel1.add(tx_firstname);
        tx_firstname.setBounds(156, 212, 285, 22);
        jPanel1.add(tx_lastname);
        tx_lastname.setBounds(156, 244, 285, 22);
        jPanel1.add(tx_ticketid);
        tx_ticketid.setBounds(156, 139, 285, 22);

        ag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90" }));
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        jPanel1.add(ag);
        ag.setBounds(156, 273, 50, 22);

        colorcombow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yellow", "Red", "Blue" }));
        colorcombow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorcombowActionPerformed(evt);
            }
        });
        jPanel1.add(colorcombow);
        colorcombow.setBounds(156, 172, 80, 22);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(260, 390, 73, 25);

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMainMenu);
        btnMainMenu.setBounds(620, 620, 95, 25);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("City");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(67, 311, 83, 16);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Number Phone");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(67, 346, 84, 16);
        jPanel1.add(tx_city);
        tx_city.setBounds(156, 308, 285, 22);
        jPanel1.add(tx_nophone);
        tx_nophone.setBounds(156, 343, 285, 22);

        btn_create.setText("Create Mode");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel1.add(btn_create);
        btn_create.setBounds(580, 210, 130, 30);

        btn_search.setText("Search ID");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(448, 138, 89, 25);

        btn_upd.setText("Update Mode");
        btn_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updActionPerformed(evt);
            }
        });
        jPanel1.add(btn_upd);
        btn_upd.setBounds(730, 210, 110, 30);

        btnUp.setText("Update");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnUp);
        btnUp.setBounds(260, 390, 73, 25);

        btn_delmode.setText("Delete Mode");
        btn_delmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delmodeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delmode);
        btn_delmode.setBounds(870, 210, 120, 30);

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(data_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(459, 273, 724, 301);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\formula\\src\\gambar\\f1star.jpg")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-20, -20, 1240, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        menu obj = new menu();
        obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
int pil = JOptionPane.showOptionDialog(this, "Do you want to delete this?", "Delete Data",
        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null,null,null);
            if(pil == JOptionPane.YES_NO_OPTION){
        try{
            sql = "DELETE FROM tbl_penonton WHERE id_ticket=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, tx_ticketid.getText());
            int rt = ps.executeUpdate();
            if(rt==0){
                JOptionPane.showMessageDialog(this, "No data");
            }else
            JOptionPane.showMessageDialog(this, "Data has successfully deleted");
        }catch (Exception e){
            System.out.println("Error"+e.getMessage());
        }
            }else{
                JOptionPane.showMessageDialog(this, "apaansi");
            }
            clear();
datatable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void colorcombowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorcombowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorcombowActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
        new audience().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String auo = tx_ticketid.getText();
        if(auo.equals("")){
            JOptionPane.showMessageDialog(this, "You search for nothing");
        }else{
        try {
            sql = "SELECT * FROM `tbl_penonton` WHERE `id_ticket` = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, auo);
            rs = ps.executeQuery();
            if(rs==null){
                JOptionPane.showMessageDialog(this, "no data");
            }
            while(rs.next()){
                colorcombow.setSelectedItem(rs.getString(2));
                tx_firstname.setText(rs.getString(3));
                tx_lastname.setText(rs.getString(4));
                ag.setSelectedItem(rs.getString(5));
                tx_city.setText(rs.getString(6));
                tx_nophone.setText(rs.getString(7));
                JOptionPane.showMessageDialog(this, "Data found");
            }
            
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
            JOptionPane.showMessageDialog(this, "No Data");
        }
        }
         btn_delete.setEnabled(true);
datatable();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updActionPerformed
        // TODO add your handling code here:
        btnUp.setVisible(true);
        btn_delete.setVisible(false);
        
        tx_city.setEnabled(true);
        tx_firstname.setEnabled(true);
        tx_lastname.setEnabled(true);
        tx_nophone.setEnabled(true);
        colorcombow.setEnabled(true);
        ag.setEnabled(true);
    }//GEN-LAST:event_btn_updActionPerformed

    private void btn_delmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delmodeActionPerformed
        // TODO add your handling code here:
        btnUp.setVisible(false);
        btn_delete.setVisible(true);
        
        tx_city.setEnabled(false);
        tx_firstname.setEnabled(false);
        tx_lastname.setEnabled(false);
        tx_nophone.setEnabled(false);
        colorcombow.setEnabled(false);
        ag.setEnabled(false);
    }//GEN-LAST:event_btn_delmodeActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if(tx_city.getText().isEmpty() || tx_firstname.getText().isEmpty() || 
                tx_lastname.getText().isEmpty() || tx_nophone.getText().isEmpty()
                || tx_ticketid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all the blanks");
        }else
        try{
            sql = "UPDATE `tbl_penonton` SET `ticket_color`=?,`firstname`=?,`lastname`=?,`age`=?,"
                    + "`city`=?,`no_phone`=?,`id_ticket`=? WHERE id_ticket=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, colorcombow.getSelectedItem().toString());
            ps.setString(2, tx_firstname.getText());
            ps.setString(3, tx_lastname.getText());
            ps.setString(4, ag.getSelectedItem().toString());
            ps.setString(5, tx_city.getText());
            ps.setString(6, tx_nophone.getText());
            ps.setString(7, tx_ticketid.getText());
            ps.setString(8, tx_ticketid.getText());
            int rt = ps.executeUpdate();
            if(rt!=0){
                JOptionPane.showMessageDialog(this, "data successfully updated");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "data gagal");
            System.out.println("Error"+e.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btnUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteaud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ag;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delmode;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_upd;
    private javax.swing.JComboBox<String> colorcombow;
    private javax.swing.JTable data_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tx_city;
    private javax.swing.JTextField tx_firstname;
    private javax.swing.JTextField tx_lastname;
    private javax.swing.JTextField tx_nophone;
    private javax.swing.JTextField tx_ticketid;
    // End of variables declaration//GEN-END:variables

private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Ticket");
        tbl.addColumn("Ticket Color");
        tbl.addColumn("Firstname");
        tbl.addColumn("Lastname");
        tbl.addColumn("Age");
        tbl.addColumn("City");
        tbl.addColumn("Number Phone");
        data_table.setModel(tbl);
        try{
            String sql = "SELECT * FROM tbl_penonton ";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object []{
                    rs.getString("id_ticket"),
                    rs.getString("ticket_color"),
                    rs.getString("firstname"),
                    rs.getString("lastname"),
                    rs.getString("age"),
                    rs.getString("city"),
                    rs.getString("no_phone")
                });
                data_table.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
private void clear(){
    tx_city.setText("");
    tx_firstname.setText("");
    tx_lastname.setText("");
    tx_nophone.setText("");
    tx_ticketid.setText("");
}
}
