package formula;

import javax.swing.table.DefaultTableModel;
import DB.DatabaseConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class registeredau extends javax.swing.JFrame {
        static Connection conn;
        static Statement st;
        static PreparedStatement ps;
        static String sql;
        static ResultSet rs;
        String[][] dataUser;
        String gbs, gbs2;
        
    public registeredau() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DatabaseConnection().setConnection();
        
        datatable();
        gbslagi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectf1PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("projectf1PU").createEntityManager();
        tblPenontonQuery = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery.getResultList();
        tblPenontonQuery1 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery1.getResultList();
        tblPemenangQuery = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPemenang t");
        tblPemenangList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPemenangQuery.getResultList();
        tblPenontonQuery2 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery2.getResultList();
        tblPenontonQuery3 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery3.getResultList();
        tblPenontonQuery4 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery4.getResultList();
        tblPemenangQuery1 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPemenang t");
        tblPemenangList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPemenangQuery1.getResultList();
        tblPenontonQuery5 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery5.getResultList();
        tblPemenangQuery2 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPemenang t");
        tblPemenangList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPemenangQuery2.getResultList();
        tblPenontonQuery6 = java.beans.Beans.isDesignTime() ? null : projectf1PUEntityManager.createQuery("SELECT t FROM TblPenonton t");
        tblPenontonList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblPenontonQuery6.getResultList();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tx_nopem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(954, 674));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registered Audience and Select Winner");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 53, 957, 29);

        btnDelete.setText("Delete and Update");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(29, 172, 137, 30);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(816, 581, 59, 25);

        jButton3.setText("Randomize");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(767, 159, 95, 25);
        getContentPane().add(tx_nopem);
        tx_nopem.setBounds(846, 119, 30, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Ticket", "Firstname", "Lastname", "Age", "City", "No Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 100, 480, 64);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Winner Number -");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(742, 122, 99, 16);

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 177, 480, 402);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\formula\\src\\gambar\\Shining-Stars-Clear-Sky.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -270, 970, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tx_nopem.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill the Winner Number");
        }else{
            if(tx_nopem.getText().equals(gbs)){
                gbslagi();
                JOptionPane.showMessageDialog(this, "Cant enter same number");
            }else{
            tabelDataUser();
            masukin();
            tx_nopem.setText("");
        }
        }
        gbslagi();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        new deleteaud().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registeredau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registeredau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registeredau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registeredau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registeredau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btn_back;
    private javax.swing.JTable data_table;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.persistence.EntityManager projectf1PUEntityManager;
    private javax.swing.JTable tblData;
    private java.util.List<formula.TblPemenang> tblPemenangList;
    private java.util.List<formula.TblPemenang> tblPemenangList1;
    private java.util.List<formula.TblPemenang> tblPemenangList2;
    private javax.persistence.Query tblPemenangQuery;
    private javax.persistence.Query tblPemenangQuery1;
    private javax.persistence.Query tblPemenangQuery2;
    private java.util.List<formula.TblPenonton> tblPenontonList;
    private java.util.List<formula.TblPenonton> tblPenontonList1;
    private java.util.List<formula.TblPenonton> tblPenontonList2;
    private java.util.List<formula.TblPenonton> tblPenontonList3;
    private java.util.List<formula.TblPenonton> tblPenontonList4;
    private java.util.List<formula.TblPenonton> tblPenontonList5;
    private java.util.List<formula.TblPenonton> tblPenontonList6;
    private javax.persistence.Query tblPenontonQuery;
    private javax.persistence.Query tblPenontonQuery1;
    private javax.persistence.Query tblPenontonQuery2;
    private javax.persistence.Query tblPenontonQuery3;
    private javax.persistence.Query tblPenontonQuery4;
    private javax.persistence.Query tblPenontonQuery5;
    private javax.persistence.Query tblPenontonQuery6;
    private javax.swing.JTextField tx_nopem;
    // End of variables declaration//GEN-END:variables

    private void tabelDataUser() {
        try {
            rs = dataUser();
            tblData.setModel(tabelModelData());
            tblData.setEnabled(false);
        } catch (Exception e) {
            e.getMessage();
        }
    }
    private DefaultTableModel tabelModelData()
    {        
        String[] namaKolom = {"id tiket","tiket color", "firstname", "lastname", "age","city","no phone"};
        int rows = 0;
        try{
            while (rs.next()){
                rows = rs.getRow();
            }
            rs.beforeFirst();
            dataUser = new String[rows][namaKolom.length];
            for (int i = 0; i < rows; i++) {
                rs.next();
                for (int j = 0; j < namaKolom.length; j++) {
                    dataUser[i][j] = rs.getString(j + 1);
                }
            }
        } catch (Exception ex){}
        return new DefaultTableModel(dataUser, namaKolom);
    }


private ResultSet dataUser() {
        try {
            String sql = "SELECT * FROM tbl_penonton order by RAND() "
                    + "LIMIT 1 ";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }
        return rs;
    }


private void masukin(){
            try{
                if(tx_nopem.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "fill Winner number");
                }else{
            sql = "INSERT INTO tbl_pemenang(ticket_win, id_ticket, ticket_color, firstname, lastname, age, city, no_phone) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ";
            ps =conn.prepareStatement(sql);
            ps.setString(1, tx_nopem.getText());
            ps.setString(2, rs.getString(1));
            ps.setString(3, rs.getString(2));
            ps.setString(4, rs.getString(3));
            ps.setString(5, rs.getString(4));
            ps.setString(6, rs.getString(5));
            ps.setString(7, rs.getString(6));
            ps.setString(8, rs.getString(7));
            int rt = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Congratulations to "+rs.getString(3)+" "+rs.getString(4));
                }
        }catch (Exception e){
            System.out.println("Error"+e.getMessage());
        }
}

 private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Ticket");
        tbl.addColumn("Ticket Color");
        tbl.addColumn("Firstname");
        tbl.addColumn("Lastname");
        tbl.addColumn("Age");
        tbl.addColumn("City");
        tbl.addColumn("Number Phone");
        data_table.setModel(tbl);
        try{
            String sql = "SELECT * FROM tbl_penonton ";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object []{
                    rs.getString("id_ticket"),
                    rs.getString("ticket_color"),
                    rs.getString("firstname"),
                    rs.getString("lastname"),
                    rs.getString("age"),
                    rs.getString("city"),
                    rs.getString("no_phone")
                });
                data_table.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

 private void gbslagi(){
            try {
                String sql = "SELECT * FROM tbl_pemenang ";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                
                while(rs.next()){
                   gbs = rs.getString("ticket_win");
                }
            } catch (SQLException ex) {   
            }
            
}
 
 
}
