package formula;
import javax.swing.JOptionPane;
import DB.DatabaseConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class vali extends javax.swing.JFrame {
        static Connection conn;
        static Statement st;
        static PreparedStatement ps;
        static String sql;
        static ResultSet rs;
        
        String gbs;
        
    public vali() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DatabaseConnection().setConnection();
        
        datatable();
        gbslagi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lapscombo = new javax.swing.JComboBox<>();
        teamcombo = new javax.swing.JComboBox<>();
        tirescombo = new javax.swing.JComboBox<>();
        circuitcombo = new javax.swing.JComboBox<>();
        drivercombo = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        btn_mainmenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tx_ticketid = new javax.swing.JTextField();
        btn_delup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F1 Registration Form");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-60, 50, 997, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Laps");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 220, 28, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Team");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 170, 34, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Tires");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 280, 28, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Circuit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 330, 38, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Driver");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 390, 37, 17);

        lapscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        lapscombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapscomboActionPerformed(evt);
            }
        });
        jPanel1.add(lapscombo);
        lapscombo.setBounds(150, 220, 123, 30);

        teamcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercedes", "Ferrari", "Alfa Romeo", "Renault", "McLaren", "Honda", "Red Bull", "BMW Sauber" }));
        jPanel1.add(teamcombo);
        teamcombo.setBounds(150, 170, 123, 30);

        tirescombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soft", "Hard", "Wet" }));
        jPanel1.add(tirescombo);
        tirescombo.setBounds(150, 270, 123, 30);

        circuitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Reversed", "Extended" }));
        jPanel1.add(circuitcombo);
        circuitcombo.setBounds(150, 330, 123, 30);

        drivercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lewis Hamilton", "Sebastian Vettel", "Daniel Ricciardo", "Max Verstappen", "Nico Hulkenberg", "Lando Norris", "Fernando Alonso", "Carlos Sainz", "Rio Haryanto", "Nico Rosberg" }));
        jPanel1.add(drivercombo);
        drivercombo.setBounds(150, 390, 123, 30);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(170, 450, 73, 25);

        btn_mainmenu.setText("Main Menu");
        btn_mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mainmenu);
        btn_mainmenu.setBounds(400, 570, 95, 25);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Number Winner");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 130, 90, 16);
        jPanel1.add(tx_ticketid);
        tx_ticketid.setBounds(150, 130, 123, 22);

        btn_delup.setText("Delete and update");
        btn_delup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delup);
        btn_delup.setBounds(511, 137, 137, 25);

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 190, 524, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\formula\\src\\gambar\\f1.png")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-19, -24, 910, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainmenuActionPerformed
       menu obj = new menu();
       obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_mainmenuActionPerformed

    private void lapscomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapscomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lapscomboActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        if(tx_ticketid.getText().isEmpty() ){
        JOptionPane.showMessageDialog(this, "please fill the coloumn");
    }else{
            if(tx_ticketid.getText().equals(gbs)){
                JOptionPane.showMessageDialog(this, "The person cant be entered again");
            }else{
            try{                
            sql = "INSERT INTO tbl_req(ticket_win, team, laps, tires, circuit, driver) VALUES (?, ?, ?, ?, ?, ? ) ";
            ps =conn.prepareStatement(sql);
            ps.setString(1, tx_ticketid.getText());
            ps.setString(2, teamcombo.getSelectedItem().toString());
            ps.setString(3, lapscombo.getSelectedItem().toString());
            ps.setString(4, tirescombo.getSelectedItem().toString());
            ps.setString(5, circuitcombo.getSelectedItem().toString());
            ps.setString(6, drivercombo.getSelectedItem().toString());
            int rt = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Success");
                
        }catch (Exception e){
            System.out.println("Error "+e.getMessage());
        }
            }
        }
        tx_ticketid.setText("");
        gbslagi();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_delupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delupActionPerformed
        // TODO add your handling code here:
        new delvali().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_delupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delup;
    private javax.swing.JButton btn_mainmenu;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> circuitcombo;
    private javax.swing.JTable data_table;
    private javax.swing.JComboBox<String> drivercombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lapscombo;
    private javax.swing.JComboBox<String> teamcombo;
    private javax.swing.JComboBox<String> tirescombo;
    private javax.swing.JTextField tx_ticketid;
    // End of variables declaration//GEN-END:variables

private void gblhksg(){
    if(circuitcombo.getSelectedItem().toString().isEmpty() || drivercombo.getSelectedItem().toString().isEmpty() ||
            lapscombo.getSelectedItem().toString().isEmpty() ||teamcombo.getSelectedItem().toString().isEmpty() ||
            tirescombo.getSelectedItem().toString().isEmpty() ){
        JOptionPane.showMessageDialog(this, "please fill all the coloumn");
    }
}

private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Pemenang ke");
        tbl.addColumn("ID Ticket");
        tbl.addColumn("Ticket Color");
        tbl.addColumn("Firstname");
        tbl.addColumn("Lastname");
        tbl.addColumn("Age");
        tbl.addColumn("City");
        tbl.addColumn("Number Phone");
        data_table.setModel(tbl);
        try{
            String sql = "SELECT * FROM tbl_pemenang ";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object []{
                    rs.getString("ticket_win"),
                    rs.getString("id_ticket"),
                    rs.getString("ticket_color"),
                    rs.getString("firstname"),
                    rs.getString("lastname"),
                    rs.getString("age"),
                    rs.getString("city"),
                    rs.getString("no_phone")
                });
                data_table.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

private void gbslagi(){
            try {
                String sql = "SELECT * FROM tbl_req ";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                
                while(rs.next()){
                   gbs = rs.getString("ticket_win");
                }
            } catch (SQLException ex) {   
            }
            
}
}
