package formula;

import DB.DatabaseConnection;
import static formula.registeredexp.st;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class whatTheySay extends javax.swing.JFrame {

    static Connection conn;
        static Statement st;
        static PreparedStatement ps;
        static String sql;
        static ResultSet rs;
        
        String gbs;
        
    public whatTheySay() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DatabaseConnection().setConnection();
        
        datatable();
        gbslagi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tx_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_testi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_adv = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();
        btn_mainmen = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("What They Say ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 61, 791, 40);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ID req");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(108, 132, 35, 16);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Testimonial");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(84, 250, 66, 16);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Advice");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(114, 364, 37, 16);
        jPanel1.add(tx_id);
        tx_id.setBounds(155, 132, 74, 22);

        ta_testi.setColumns(20);
        ta_testi.setRows(5);
        jScrollPane1.setViewportView(ta_testi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(155, 250, 468, 96);

        ta_adv.setColumns(20);
        ta_adv.setRows(5);
        jScrollPane2.setViewportView(ta_adv);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(155, 364, 468, 96);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(325, 467, 73, 25);

        btn_mainmen.setText("Main Menu");
        btn_mainmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainmenActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mainmen);
        btn_mainmen.setBounds(314, 534, 95, 25);

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(data_table);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(236, 119, 386, 94);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\formula\\src\\gambar\\Shining-Stars-Clear-Sky.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-9, -30, 840, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if(tx_id.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please insert the ID first");
        }else{
            if(tx_id.getText().equals(gbs)){
                JOptionPane.showMessageDialog(this, "The person cant be entered again");
            }else{
        try {
            sql = "INSERT INTO tbl_exp(id_req, testimoni, adv) VALUES (?, ?, ?) ";
            ps =conn.prepareStatement(sql);
            ps.setString(1, tx_id.getText());
            ps.setString(2, ta_testi.getText());
            ps.setString(3, ta_adv.getText());
            int rt = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Succes");
                
        }catch (Exception e){
            System.out.println("Error"+e.getMessage());  
        }
        }
        }
        datatable();
        clearall();
        gbslagi();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_mainmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainmenActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mainmenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(whatTheySay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(whatTheySay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(whatTheySay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(whatTheySay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new whatTheySay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mainmen;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTable data_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea ta_adv;
    private javax.swing.JTextArea ta_testi;
    private javax.swing.JTextField tx_id;
    // End of variables declaration//GEN-END:variables

private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Req");
        tbl.addColumn("Ticket Win");
        tbl.addColumn("Team");
        tbl.addColumn("Laps");
        tbl.addColumn("Tires");
        tbl.addColumn("Circuit");
        tbl.addColumn("Driver");
        data_table.setModel(tbl);
        try{
            String sql = "SELECT * FROM tbl_req ";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object []{
                    rs.getString("id_req"),
                    rs.getString("ticket_win"),
                    rs.getString("team"),
                    rs.getString("laps"),
                    rs.getString("tires"),
                    rs.getString("circuit"),
                    rs.getString("driver")
                });
                data_table.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

private void clearall(){
    tx_id.setText("");
    ta_adv.setText("");
    ta_testi.setText("");
}

private void gbslagi(){
            try {
                String sql = "SELECT * FROM tbl_exp ";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                
                while(rs.next()){
                   gbs = rs.getString("id_req");
                }
            } catch (SQLException ex) {   
            }
            
}

}
